#!/usr/bin/env python3
"""cc-cairn — Cairness framework project CLI.

Usage:
    cc-cairn init                                Initialize Cairness in the current project
    cc-cairn onboard [--dry-run] [--yes]         Inspect and initialize a project safely
    cc-cairn update                              Pull latest release and update framework
    cc-cairn version                             Show installed and project versions
    cc-cairn doctor [--json] [--fix] [--apply]   Diagnose and safely repair readiness
    cc-cairn explain COMMAND [--change ID]         Show the effective runtime contract
    cc-cairn loop enable                         Enable Loop Engineering (autonomous) mode
    cc-cairn loop disable                        Disable Loop Engineering, revert to standard
    cc-cairn loop status                         Show current loop mode status
    cc-cairn add-knowledge [--apply] PATH...     Register knowledge files into index.md
    cc-cairn add-knowledge --remove [--apply] PATH...  Remove entries from index.md
    cc-cairn add-knowledge --rename [--apply] OLD NEW  Rename an entry's path
"""

import argparse
import json
import re
import os
import sys
import shutil
import subprocess
import tempfile
from pathlib import Path

SCRIPTS_DIR = Path(__file__).resolve().parent / "scripts"
if str(SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPTS_DIR))

from harness_runtime.config import HarnessConfigError, load_harness_config
from harness_runtime.context import (
    HarnessContextError,
    load_harness_context,
    resolve_framework_root,
)
from harness_runtime.doctor import apply_fix_plan, build_doctor_report, fix_plan
from harness_runtime.explain import build_effective_contract
from harness_runtime.adapter_installation import (
    AdapterInstallationError,
    build_adapter_installation_plan,
    load_adapter_installation,
)
from harness_runtime.runtime_layout import RuntimeLayout
from harness_runtime.versioning import VersionMetadataError, read_version
from harness_runtime.onboarding import (
    INSTALL_METADATA_RELATIVE,
    build_plan,
    inspect_project,
    read_install_metadata,
    write_install_metadata,
)
from harness_runtime.product_profiles import (
    apply_product_profile,
    build_profile_plan,
    list_product_profiles,
)

MIN_PYTHON = (3, 9)
REMOTE_URL = "https://github.com/lq5657/Cairness.git"

CI_TEMPLATE_DIR = "templates/ci"

ADAPTER_INSTALLATION_SCHEMA = "schemas/adapter-installation.schema.json"
ADAPTER_INSTALLATION_DIR = "runtime/adapters"
UPGRADE_REPORT_RELATIVE = Path(".cairness/upgrade-report.json")

STATE_SKELETON = [
    ".cairness/context",
    ".cairness/changes",
    ".cairness/audits",
    ".cairness/knowledge",
    ".cairness/discussions",
    ".cairness/loop-audit",  # Loop Engineering async audit log (only written in loop profile)
]

KNOWLEDGE_CATALOG_REL = "runtime/knowledge-categories.yaml"

KNOWLEDGE_TEMPLATE = "templates/knowledge/index.md"
KNOWLEDGE_TARGET = ".cairness/knowledge/index.md"

GITIGNORE_ADDITIONS = """
# Cairness framework (managed by cc-cairn)
.claude/
# Per-machine verification baselines: transient snapshots written by cc-role-check
# (role-baseline.json) and cc-verify (pre-apply.json) during the apply/review loop.
# Never shared or committed — they reflect local worktree state and diverge per machine.
.cairness/changes/*/baseline/
# Loop Engineering audit logs: auto-generated by cc-self-eval during loop execution.
# Untrack by default — remove this line if you want to commit audit history to the repo.
.cairness/loop-audit/
"""


BASELINE_GITIGNORE_RULE = ".cairness/changes/*/baseline/"


# Files the release ships but whose local version must survive an upgrade
# (these are user-local state, not framework assets).
PRESERVE_ON_UPGRADE = {"settings.local.json"}

# Framework version-metadata files that legitimately change on every upgrade.
# They are not user customizations, so excluded from the upgrade merge report
# (reporting them would be noise on every upgrade).
UPGRADE_META_FILES = {"VERSION", "CHANGELOG.md", "UPGRADE.md"}

# Patterns excluded from every ship copy. Dev-local / build artifacts that must
# never reach a target project. settings.local.json is also a PRESERVE_ON_UPGRADE
# file: on upgrade the user's version is carried forward from the backup, so this
# ignore only stops the release's own copy landing fresh — it never ships a dev
# permission whitelist into a new project. Keep in sync with SHIP_IGNORE in
# cairn_install.
SHIP_IGNORE = shutil.ignore_patterns(
    "__pycache__", "*.pyc", "node_modules", "settings.local.json",
)

# Framework-controlled, non-user-extensible top-level dirs under .claude/.
# A file absent from the new release inside one of these is a framework
# removal, NOT a user file, and must not be carried forward on upgrade —
# otherwise a removed artifact like runtime/readsets/cc-help.yaml resurrects
# and trips E_READSET009 / E_SCHEMA152. User-extensible framework dirs
# (hooks/, scripts/, skills/) are intentionally NOT listed, so user-added
# files there still survive; so do root-level user CC config (settings.json,
# agents/, commands/, mcp.json, ...).
FRAMEWORK_OWNED_DIRS = frozenset({
    "runtime", "schemas", "templates", "rules",
    "references", "docs", "evals", "fixtures", "workflows",
})


def _is_framework_owned(rel: str) -> bool:
    """True if ``rel`` lives under a framework-controlled, non-user-extensible dir."""
    top = rel.split("/", 1)[0]
    return top in FRAMEWORK_OWNED_DIRS


class UpgradeSafetyError(Exception):
    """Raised when an upgrade would unsafely clobber state."""


def _rel_file_set(root: Path) -> set[str]:
    """Posix-relative paths of every regular file under ``root``."""
    out: set[str] = set()
    if not root.exists():
        return out
    for p in root.rglob("*"):
        if p.is_file():
            out.add(p.relative_to(root).as_posix())
    return out


def _modified_framework_files(backup: Path, src: Path) -> list[str]:
    """User-customized framework files that the fresh swap overwrites.

    rel paths present in both ``backup`` (user's old version) and ``src`` (new
    release) whose bytes differ. Excludes ``PRESERVE_ON_UPGRADE`` (kept, not
    overwritten) and user-added files (absent from src, carried forward
    separately). Used for the upgrade merge report — does not alter overwrite
    semantics.
    """
    src_files = _rel_file_set(src)
    modified: list[str] = []
    for rel in sorted(_rel_file_set(backup)):
        if rel in PRESERVE_ON_UPGRADE or rel in UPGRADE_META_FILES or rel not in src_files:
            continue
        if (backup / rel).read_bytes() != (src / rel).read_bytes():
            modified.append(rel)
    return modified


def _replace_framework_dir(
    src: Path,
    dst: Path,
    *,
    label: str,
    force: bool = False,
) -> Path | None:
    """Safely replace ``dst`` with a fresh copy of ``src``.

    Used by init/update for both the project ``.claude/`` and the system
    install dir. Replaces the previous ``rmtree + copytree`` which silently
    destroyed any local modifications with no recovery path.

    Safety properties:
      * Identity check: if ``dst`` exists but has no ``VERSION`` file it is
        treated as a foreign directory and refused unless ``force=True``
        (prevents clobbering a non-Cairness ``.claude/``).
      * Backup: the previous ``dst`` is moved to ``<dst>.bak`` (one backup
        retained) so local changes are always recoverable.
      * Atomic-ish swap: the fresh tree is built in a temp dir beside ``dst``
        and renamed into place; on failure the backup is restored.
      * Preservation: files present in the old ``dst`` but absent from ``src``
        (user-added hooks/scripts) are copied back, and files in
        ``PRESERVE_ON_UPGRADE`` keep the user's local version. Files absent
        from ``src`` inside ``FRAMEWORK_OWNED_DIRS`` are framework removals,
        not user files — they are dropped (recoverable in the backup) so a
        removed artifact like ``runtime/readsets/cc-help.yaml`` cannot
        resurrect and trip ``E_READSET009`` / ``E_SCHEMA152``.

    Returns the backup ``Path`` if one was made, else ``None``.
    """
    parent = dst.parent
    parent.mkdir(parents=True, exist_ok=True)

    if dst.name == ".cairness":
        raise UpgradeSafetyError(
            f"Refusing to replace {dst}: '.cairness/' is project state, "
            f"not a replaceable framework root."
        )

    had_existing = dst.exists()
    backup: Path | None = None

    if had_existing:
        if not force and not (dst / "VERSION").is_file():
            raise UpgradeSafetyError(
                f"{dst} exists but is not a Cairness install (no VERSION file). "
                f"Refusing to overwrite a foreign directory. Re-run with --force "
                f"to override."
            )
        backup = dst.with_name(dst.name + ".bak")
        if backup.exists():
            shutil.rmtree(backup)
        os.rename(dst, backup)

    # Build the fresh tree in a temp dir beside dst, then rename into place.
    tmp = Path(tempfile.mkdtemp(prefix=dst.name + ".tmp-", dir=str(parent)))
    try:
        # tmp is an empty dir created by mkdtemp; copy into it.
        shutil.copytree(src, tmp, dirs_exist_ok=True, ignore=SHIP_IGNORE)
        os.rename(tmp, dst)
    except Exception:
        if tmp.exists():
            shutil.rmtree(tmp, ignore_errors=True)
        if backup is not None and backup.exists() and not dst.exists():
            os.rename(backup, dst)
        raise

    # Carry forward user-added files and protected local files from the backup.
    # Files absent from the new source inside FRAMEWORK_OWNED_DIRS are framework
    # removals, not user files — drop them instead of resurrecting stale
    # artifacts (e.g. a removed runtime/readsets/cc-help.yaml). Dropped files
    # stay recoverable in the backup.
    if backup is not None and backup.exists():
        src_files = _rel_file_set(src)
        dropped: list[str] = []
        for rel in sorted(_rel_file_set(backup)):
            if rel in PRESERVE_ON_UPGRADE or rel not in src_files:
                if rel not in src_files and _is_framework_owned(rel):
                    dropped.append(rel)
                    continue
                src_file = backup / rel
                target = dst / rel
                target.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(src_file, target)
        if dropped:
            print(f"  {len(dropped)} stale framework file(s) removed by this upgrade "
                  f"(retained in {backup.name}/):")
            for rel in dropped:
                print(f"    - {rel}")

    # Merge report: surface user-customized framework files that the fresh
    # swap overwrote. Report-only — overwrite semantics are unchanged; the
    # user's versions remain in the backup for re-application.
    if backup is not None and backup.exists():
        modified = _modified_framework_files(backup, src)
        if modified:
            print(f"  {len(modified)} framework file(s) you customized were overwritten by the new version:")
            for rel in modified:
                print(f"    - {rel}")
            print(f"  Your versions are retained in {backup.name}/ ; re-apply customizations or diff against the new files.")
            report_path = dst.parent / f"{dst.name}.merge-report.json"
            report_path.write_text(
                json.dumps({"overwritten_modified_files": modified}, ensure_ascii=False, indent=2) + "\n",
                encoding="utf-8",
            )
            print(f"  Merge report: {report_path}")

    if backup is not None:
        print(f"  Previous {label} backed up to: {backup}")
    return backup


def _adapter_installation_plan(data_dir: Path, project_root: Path, adapter: str):
    """Load and resolve one declared adapter before making project changes."""
    manifest = data_dir / ADAPTER_INSTALLATION_DIR / f"{adapter}.yaml"
    installation = load_adapter_installation(
        manifest, data_dir / ADAPTER_INSTALLATION_SCHEMA
    )
    plan = build_adapter_installation_plan(
        installation, core_root=data_dir, project_root=project_root
    )
    if plan.adapter != adapter:
        raise AdapterInstallationError(
            f"adapter installation identity {plan.adapter!r} does not match "
            f"requested adapter {adapter!r}"
        )
    unsupported = [op.name for op in plan.operations if op.action == "generate"]
    if unsupported:
        raise ValueError(
            "adapter installation generate operations are not supported: "
            + ", ".join(unsupported)
        )
    return plan


def _framework_root_from_prefix(project_root: Path, framework_prefix: str) -> Path:
    """Resolve persisted layout metadata without allowing project escape."""
    root = Path(project_root).resolve()
    layout = RuntimeLayout(
        project_root=root,
        core_root=root / framework_prefix,
        state_root=root / ".cairness",
        framework_prefix=framework_prefix,
    )
    framework_root = layout.core_root
    try:
        framework_root.relative_to(root)
    except ValueError as exc:
        raise ValueError(
            f"framework prefix escapes the project root: {framework_prefix!r}"
        ) from exc
    return framework_root


def _restore_failed_adapter_swap(
    framework_root: Path, backup: Path | None
) -> None:
    """Roll back a completed core swap when a host-asset operation fails."""
    if framework_root.exists():
        shutil.rmtree(framework_root)
    if backup is not None and backup.exists():
        os.rename(backup, framework_root)


def _file_snapshot(path: Path) -> bytes | None:
    """Capture an optional small state file for post-swap rollback."""
    return path.read_bytes() if path.is_file() else None


def _restore_file_snapshot(path: Path, snapshot: bytes | None) -> None:
    """Restore the exact pre-update state of an optional state file."""
    if snapshot is None:
        path.unlink(missing_ok=True)
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(snapshot)


def _file_state_snapshot(path: Path) -> tuple[bytes, int] | None:
    """Capture file content and permissions for rollback of executable hooks."""
    if not path.is_file():
        return None
    return path.read_bytes(), path.stat().st_mode


def _restore_file_state_snapshot(
    path: Path, snapshot: tuple[bytes, int] | None
) -> None:
    if snapshot is None:
        path.unlink(missing_ok=True)
        return
    content, mode = snapshot
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(content)
    path.chmod(mode)


def _directory_file_snapshots(path: Path) -> dict[str, tuple[bytes, int]]:
    if not path.is_dir():
        return {}
    return {
        item.name: snapshot
        for item in path.iterdir()
        if item.is_file() and (snapshot := _file_state_snapshot(item)) is not None
    }


def _restore_directory_file_snapshots(
    path: Path, snapshots: dict[str, tuple[bytes, int]], *, existed: bool
) -> None:
    if path.is_dir():
        for item in path.iterdir():
            if item.is_file() and item.name not in snapshots:
                item.unlink()
    for name, snapshot in snapshots.items():
        _restore_file_state_snapshot(path / name, snapshot)
    if not existed and path.is_dir():
        try:
            path.rmdir()
        except OSError:
            pass


def _existing_directories(root: Path) -> set[Path]:
    if not root.is_dir():
        return set()
    return {root, *(path for path in root.rglob("*") if path.is_dir())}


def _remove_new_empty_directories(root: Path, existing: set[Path]) -> None:
    if not root.exists():
        return
    directories = [path for path in root.rglob("*") if path.is_dir()]
    directories.append(root)
    for path in sorted(directories, key=lambda item: len(item.parts), reverse=True):
        if path not in existing:
            try:
                path.rmdir()
            except OSError:
                pass


def _require_custom_layout_identity(
    framework_root: Path, *, adapter: str, contract_prefix: str, selected_prefix: str
) -> None:
    """Reject metadata redirects that do not identify an installed adapter."""
    if selected_prefix == contract_prefix:
        return
    manifest = framework_root / ADAPTER_INSTALLATION_DIR / f"{adapter}.yaml"
    schema = framework_root / ADAPTER_INSTALLATION_SCHEMA
    try:
        installation = load_adapter_installation(manifest, schema)
    except (OSError, ValueError) as exc:
        raise ValueError(
            f"custom framework layout {selected_prefix!r} has no valid "
            f"adapter installation identity for {adapter!r}: {manifest}"
        ) from exc
    if (
        installation.adapter != adapter
        or installation.framework_prefix != selected_prefix
    ):
        raise ValueError(
            f"custom framework layout {selected_prefix!r} adapter installation "
            f"identity does not match {adapter!r}: {manifest}"
        )


def _publish_install_result(
    project_root: Path,
    *,
    adapter: str,
    framework_prefix: str,
    report: dict,
) -> None:
    """Publish install metadata and report as one rollback-safe record pair."""
    metadata_path = project_root / INSTALL_METADATA_RELATIVE
    report_path = project_root / UPGRADE_REPORT_RELATIVE
    metadata_snapshot = _file_snapshot(metadata_path)
    report_snapshot = _file_snapshot(report_path)
    try:
        _write_install_identity(
            project_root,
            adapter=adapter,
            framework_prefix=framework_prefix,
        )
        _write_upgrade_report(project_root, report)
    except Exception:
        _restore_file_snapshot(metadata_path, metadata_snapshot)
        _restore_file_snapshot(report_path, report_snapshot)
        raise


def _execute_adapter_operations(plan, framework_root: Path) -> list[dict[str, str]]:
    """Apply validated copy operations to an already-installed core tree."""
    applied: list[dict[str, str]] = []
    for operation in plan.operations:
        relative = operation.target.relative_to(plan.framework_root)
        target = framework_root / relative
        if operation.action == "copy-file":
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(operation.source, target)
        elif operation.action == "copy-tree":
            shutil.copytree(
                operation.source,
                target,
                dirs_exist_ok=True,
                ignore=SHIP_IGNORE,
            )
        else:
            raise ValueError(
                f"unsupported adapter installation action: {operation.action}"
            )
        applied.append(
            {
                "name": operation.name,
                "action": operation.action,
                "source": operation.source.relative_to(plan.core_root).as_posix(),
                "target": relative.as_posix(),
            }
        )
    return applied


def _upgrade_file_changes(src: Path, dst: Path) -> dict[str, list[str]]:
    """Describe upgrade effects before the framework swap mutates ``dst``."""
    if not dst.exists():
        return {
            "overwritten_modified_files": [],
            "dropped_stale_files": [],
            "preserved_files": [],
        }
    src_files = _rel_file_set(src)
    old_files = _rel_file_set(dst)
    return {
        "overwritten_modified_files": _modified_framework_files(dst, src),
        "dropped_stale_files": sorted(
            rel for rel in old_files - src_files if _is_framework_owned(rel)
        ),
        "preserved_files": sorted(
            rel
            for rel in old_files
            if rel in PRESERVE_ON_UPGRADE
            or (rel not in src_files and not _is_framework_owned(rel))
        ),
    }


def _write_upgrade_report(project_root: Path, report: dict) -> Path:
    """Atomically publish a completed installation or upgrade report."""
    path = project_root / UPGRADE_REPORT_RELATIVE
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, temporary = tempfile.mkstemp(
        prefix=".upgrade-report.", suffix=".tmp", dir=path.parent
    )
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as stream:
            json.dump(report, stream, ensure_ascii=False, indent=2)
            stream.write("\n")
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temporary, path)
    except Exception:
        try:
            os.unlink(temporary)
        except OSError:
            pass
        raise
    return path


def _write_install_identity(
    project_root: Path, *, adapter: str, framework_prefix: str
) -> Path:
    metadata = read_install_metadata(project_root)
    metadata.update(
        {
            "version": 1,
            "adapter": adapter,
            "framework_prefix": framework_prefix,
        }
    )
    return write_install_metadata(project_root, metadata)


def _copy_ci_templates(ci_src: Path, ci_dst: Path) -> None:
    """Copy CI workflow templates without clobbering user-edited files.

    Existing files that differ from the template are written to
    ``<name>.cairness.new`` with a warning instead of being overwritten.
    """
    if not ci_src.exists():
        return
    ci_dst.mkdir(parents=True, exist_ok=True)
    for f in ci_src.iterdir():
        if not f.is_file():
            continue
        target = ci_dst / f.name
        if target.exists() and target.read_bytes() != f.read_bytes():
            alt = ci_dst / (f.name + ".cairness.new")
            shutil.copy2(f, alt)
            print(f"  CI template {f.name} differs from existing; wrote {alt.name} (review and merge manually)")
        else:
            shutil.copy2(f, target)
            print(f"  .github/workflows/{f.name}")


def get_data_dir():
    system = sys.platform
    home = Path.home()
    if system == "linux":
        return home / ".local" / "share" / "cairness"
    elif system == "darwin":
        return home / "Library" / "Application Support" / "cairness"
    elif system == "win32":
        local = os.environ.get("LOCALAPPDATA", str(home / "AppData" / "Local"))
        return Path(local) / "cairness"
    else:
        sys.exit(f"Unsupported platform: {system}")


def git_head_commit(repo):
    result = subprocess.run(
        ["git", "rev-parse", "HEAD"],
        cwd=repo, capture_output=True, text=True
    )
    if result.returncode != 0:
        sys.exit(f"git rev-parse failed: {result.stderr}")
    return result.stdout.strip()


def read_commit_hash(directory):
    cf = directory / "COMMIT"
    if cf.exists():
        return cf.read_text().strip()
    return None


def write_commit_hash(directory, commit):
    (directory / "COMMIT").write_text(commit + "\n")


def _finish_project_init(
    *, project_root, framework_dir, plan, data_dir, from_version, backup, changes, operations
):
    print("  Copied framework core.")
    for d in STATE_SKELETON:
        (project_root / d).mkdir(parents=True, exist_ok=True)
        print(f"  {d}/")

    knowledge_root = project_root / ".cairness" / "knowledge"
    for sub in _knowledge_init_subdirs(project_root):
        (knowledge_root / sub).mkdir(parents=True, exist_ok=True)
    print("  .cairness/knowledge/ subdirectories")

    tmpl = framework_dir / KNOWLEDGE_TEMPLATE
    dst = project_root / KNOWLEDGE_TARGET
    if tmpl.exists() and not dst.exists():
        shutil.copy2(tmpl, dst)
        print(f"  {KNOWLEDGE_TARGET} (from template)")

    ci_src = framework_dir / CI_TEMPLATE_DIR
    ci_dst = project_root / ".github" / "workflows"
    if ci_src.exists():
        print("  CI templates:")
        _copy_ci_templates(ci_src, ci_dst)

    gitignore = project_root / ".gitignore"
    existing = gitignore.read_text() if gitignore.exists() else ""
    framework_ignore = f"{plan.framework_prefix}/"
    if framework_ignore not in existing:
        with gitignore.open("a") as f:
            f.write(GITIGNORE_ADDITIONS.replace(".claude/", framework_ignore, 1))
        print("  Updated .gitignore")

    _install_git_hooks(project_root, framework_dir)

    version = (data_dir / "VERSION").read_text().strip()
    _publish_install_result(
        project_root,
        adapter=plan.adapter,
        framework_prefix=plan.framework_prefix,
        report={
            "version": 1,
            "status": "passed",
            "adapter": plan.adapter,
            "source_layout": plan.framework_prefix if from_version else "",
            "target_layout": plan.framework_prefix,
            "from_version": from_version,
            "to_version": version,
            "backup": str(backup) if backup else "",
            "legacy_migration": False,
            "operations": operations,
            **changes,
        },
    )
    print(f"\nCairness v{version} initialized for {plan.adapter}.")


def cmd_init(*, adapter="claude-code", assume_yes=False, force_foreign=False):
    data_dir = get_data_dir()
    if not data_dir.exists():
        sys.exit(f"Framework not installed. Run 'cairn_install' from the Cairness repo first.")

    project_root = Path.cwd()
    plan = _adapter_installation_plan(data_dir, project_root, adapter)
    framework_dir = plan.framework_root

    if framework_dir.exists():
        if not (framework_dir / "VERSION").is_file():
            print(f"{plan.framework_prefix}/ already exists in {project_root} but is not a Cairness install.")
            resp = "y" if (assume_yes or force_foreign) else input("Overwrite this foreign directory anyway? [y/N] ").strip().lower()
            if resp != "y":
                print("Aborted.")
                return
            force = True
        else:
            print(f"{plan.framework_prefix}/ already exists in {project_root}")
            resp = "y" if assume_yes else input("Overwrite? This will replace framework files (local additions are preserved). [y/N] ").strip().lower()
            if resp != "y":
                print("Aborted.")
                return
            force = False
    else:
        force = False

    from_version = ""
    version_path = framework_dir / "VERSION"
    if version_path.is_file():
        from_version = version_path.read_text(encoding="utf-8").strip()
    changes = _upgrade_file_changes(data_dir, framework_dir)
    print(f"Installing Cairness framework to {framework_dir} ...")
    install_path = project_root / INSTALL_METADATA_RELATIVE
    report_path = project_root / UPGRADE_REPORT_RELATIVE
    install_snapshot = _file_snapshot(install_path)
    report_snapshot = _file_snapshot(report_path)
    hook_path = project_root / ".git" / "hooks" / "pre-commit"
    hook_backup_path = hook_path.with_suffix(".bak")
    hook_snapshot = _file_state_snapshot(hook_path)
    hook_backup_snapshot = _file_state_snapshot(hook_backup_path)
    gitignore_path = project_root / ".gitignore"
    gitignore_snapshot = _file_snapshot(gitignore_path)
    knowledge_path = project_root / KNOWLEDGE_TARGET
    knowledge_snapshot = _file_snapshot(knowledge_path)
    state_root = project_root / ".cairness"
    state_directories = _existing_directories(state_root)
    ci_path = project_root / ".github" / "workflows"
    ci_existed = ci_path.is_dir()
    ci_snapshots = _directory_file_snapshots(ci_path)
    backup = _replace_framework_dir(
        data_dir, framework_dir, label="framework", force=force
    )
    try:
        operations = _execute_adapter_operations(plan, framework_dir)
        _finish_project_init(
            project_root=project_root,
            framework_dir=framework_dir,
            plan=plan,
            data_dir=data_dir,
            from_version=from_version,
            backup=backup,
            changes=changes,
            operations=operations,
        )
    except Exception:
        _restore_failed_adapter_swap(framework_dir, backup)
        _restore_file_snapshot(install_path, install_snapshot)
        _restore_file_snapshot(report_path, report_snapshot)
        _restore_file_state_snapshot(hook_path, hook_snapshot)
        _restore_file_state_snapshot(hook_backup_path, hook_backup_snapshot)
        _restore_file_snapshot(gitignore_path, gitignore_snapshot)
        _restore_file_snapshot(knowledge_path, knowledge_snapshot)
        _restore_directory_file_snapshots(
            ci_path, ci_snapshots, existed=ci_existed
        )
        _remove_new_empty_directories(state_root, state_directories)
        raise
    # Baseline cleanup is repository hygiene rather than installation identity,
    # so run it only after the framework and record pair have committed.
    _ensure_baseline_gitignored(project_root)


def cmd_onboard(argv):
    """Inspect a project, show a deterministic plan, and optionally apply it."""
    parser = argparse.ArgumentParser(prog="cc-cairn onboard")
    parser.add_argument("--adapter", default="claude-code", choices=("claude-code",))
    parser.add_argument(
        "--profile",
        default="standard",
        choices=("minimal", "standard", "strict", "loop"),
        help="runtime governance profile (default: standard)",
    )
    parser.add_argument("--language", dest="language", choices=("golang", "python", "java", "cpp", "typescript"), help="override language detection")
    parser.add_argument("--dry-run", action="store_true", help="inspect and print the plan without changing files")
    parser.add_argument("--yes", action="store_true", help="apply without confirmation prompts")
    parser.add_argument("--json", action="store_true", help="emit the plan as JSON")
    args = parser.parse_args(argv)

    root = Path.cwd().resolve()
    selected_profile = args.profile
    inspection = inspect_project(root)
    if args.language:
        inspection["language"] = {
            "status": "resolved",
            "language": args.language,
            "profile": args.language,
            "source": "cli",
            "matches": [args.language],
            "reasons": ["explicit --language selection"],
        }
        inspection["language_profile"] = args.language
    plan = build_plan(
        inspection,
        adapter=args.adapter,
        profile=selected_profile,
        language_profile=args.language,
    )
    if args.json or args.dry_run:
        print(json.dumps(plan, ensure_ascii=False, indent=2))
    else:
        print("Cairness onboarding")
        print(f"  Project: {inspection['project_type']} ({root})")
        print(f"  Framework: {inspection['framework_status']}")
        language = inspection.get("language", {})
        print(f"  Language: {language.get('language') or language.get('status', 'unknown')}")
        print(f"  Adapter: {args.adapter}  Profile: {selected_profile}")
        print("  Planned actions:")
        for action in plan["actions"]:
            target = action.get("path") or action.get("profile") or action.get("adapter") or "project"
            print(f"    - {action['action']}: {target}")

    if args.dry_run or args.json:
        return
    if inspection["language"].get("status") != "resolved":
        raise SystemExit(
            "Onboarding cannot select a language profile deterministically; "
            "rerun with --language <golang|python|java|cpp|typescript>."
        )
    if plan["status"] == "requires_confirmation" and not args.yes:
        print("Onboarding needs confirmation because existing project state may be affected.")
        if input("Apply this plan? [y/N] ").strip().lower() != "y":
            print("Aborted. No files were changed.")
            return

    force_foreign = inspection["framework_status"] in {"foreign", "partial"}
    try:
        if inspection["framework_status"] == "installed":
            for relative in ("context", "changes", "audits", "knowledge", "discussions"):
                (root / ".cairness" / relative).mkdir(parents=True, exist_ok=True)
            print("Onboarding verified existing Cairness installation.")
        else:
            cmd_init(
                adapter=args.adapter,
                assume_yes=True,
                force_foreign=force_foreign,
            )
        identity = read_install_metadata(root)
        framework_prefix = identity.get("framework_prefix", ".claude")
        _apply_runtime_profile(root / framework_prefix, selected_profile)
        metadata = dict(identity)
        metadata.update(plan["metadata"])
        metadata["framework_prefix"] = framework_prefix
        path = write_install_metadata(root, metadata)
    except (OSError, ValueError) as exc:
        print(f"Onboarding failed: {exc}", file=sys.stderr)
        raise SystemExit(1)
    report = _run_onboarding_doctor(root)
    print(f"  Wrote {path.relative_to(root)}")
    print(f"  Doctor: {report['status']}")
    if report["status"] != "passed":
        raise SystemExit(f"Onboarding failed: Doctor reported {report['status']}")
    print(f"Next command: {plan['next_command']}")


def _apply_runtime_profile(framework_root, profile):
    """Atomically update the schema-backed runtime profile."""
    config = Path(framework_root) / "harness.config.yaml"
    if not config.is_file():
        raise ValueError(f"missing harness config: {config}")
    text = config.read_text(encoding="utf-8")
    replacement = f"profile: {profile}"
    updated, count = re.subn(r"(?m)^profile:\s*[^\n]*$", replacement, text, count=1)
    if count == 0:
        raise ValueError(f"missing profile field: {config}")
    if updated != text:
        fd, temporary = tempfile.mkstemp(prefix=".harness-config.", suffix=".tmp", dir=config.parent)
        try:
            with os.fdopen(fd, "w", encoding="utf-8") as stream:
                stream.write(updated)
                stream.flush()
                os.fsync(stream.fileno())
            os.replace(temporary, config)
        except Exception:
            try:
                os.unlink(temporary)
            except OSError:
                pass
            raise


def _run_onboarding_doctor(project_root):
    """Run the product Doctor against the newly onboarded project."""
    root = Path(project_root).resolve()
    framework_prefix = read_install_metadata(root).get("framework_prefix", ".claude")
    framework_root = root / framework_prefix
    return build_doctor_report(root, framework_root, get_data_dir())


def find_repo():
    d = Path.cwd()
    while d != d.parent:
        if (d / "cairn-core" / "VERSION").exists() and (d / "cairn_install").exists():
            return d
        d = d.parent
    return None


def pull_repo(repo):
    result = subprocess.run(
        ["git", "pull", "origin", "main"],
        cwd=repo, capture_output=True, text=True
    )
    if result.returncode != 0:
        sys.exit(f"git pull failed: {result.stderr}")
    return result.stdout.strip()


def _repo_remote_url(repo):
    """Return origin URL for repo, or '' if unavailable / not a git repo."""
    result = subprocess.run(
        ["git", "remote", "get-url", "origin"],
        cwd=repo, capture_output=True, text=True
    )
    if result.returncode != 0:
        return ""
    return result.stdout.strip()


def ensure_repo():
    repo = find_repo()
    if repo is not None:
        remote = _repo_remote_url(repo)
        if remote and remote != REMOTE_URL:
            # Found a local checkout (e.g. a fork) whose origin is not the
            # official upstream. Don't surprise-pull; use it as-is so the user
            # controls updates to their own checkout.
            print(f"Using local Cairness checkout at {repo}")
            print(f"  (origin={remote} != {REMOTE_URL}; skipping auto-pull. "
                  f"Update the checkout manually if needed.)")
            return repo
        return repo

    clone_path = Path.home() / ".local" / "share" / "cairness-repo"
    if not clone_path.exists():
        print(f"Cloning Cairness from {REMOTE_URL} ...")
        result = subprocess.run(
            ["git", "clone", REMOTE_URL, str(clone_path)],
            capture_output=True, text=True
        )
        if result.returncode != 0:
            sys.exit(f"git clone failed: {result.stderr}")
    return clone_path


def sync_system_install(data_dir, repo):
    """Update system installation from repo. Returns True if updated."""
    print("Pulling latest from remote ...")
    pull_repo(repo)

    new_commit = git_head_commit(repo)
    old_commit = read_commit_hash(data_dir)

    if old_commit == new_commit:
        version = "unknown"
        vf = repo / "cairn-core" / "VERSION"
        if vf.exists():
            version = vf.read_text().strip()
        print(f"System installation already up to date (v{version}, {new_commit[:7]}).")
        return data_dir  # no update needed

    core_src = repo / "cairn-core"
    new_ver = (core_src / "VERSION").read_text().strip()
    old_ver = "none"
    vf = data_dir / "VERSION"
    if vf.exists():
        old_ver = vf.read_text().strip()

    print(f"Updating system installation: v{old_ver} → v{new_ver}")
    _replace_framework_dir(core_src, data_dir, label="system install")
    write_commit_hash(data_dir, new_commit)
    print(f"System installation updated to v{new_ver} ({new_commit[:7]}).")
    return data_dir


def _ensure_baseline_gitignored(project_root):
    """Ensure transient per-machine verification baselines stay out of git.

    Two effects, both idempotent:
      1. Append the baseline/ gitignore rule if missing (covers new installs and
         projects whose .gitignore predates the rule).
      2. `git rm --cached` any already-tracked baseline files (role-baseline.json,
         pre-apply.json, ...) so the next commit removes them from version control.
         gitignore only blocks untracked files; tracked ones must be unstaged.

    Baselines are per-machine worktree snapshots, not team-shared truth —
    committing them causes cross-machine noise and false conflicts. Safe to run
    repeatedly; silently no-ops when there is nothing to do or git is absent.
    """
    gitignore = project_root / ".gitignore"
    existing = gitignore.read_text() if gitignore.exists() else ""
    if BASELINE_GITIGNORE_RULE not in existing:
        # Ensure the rule sits under a Cairness header if we wrote one; append
        # is sufficient since gitignore rules are order-independent.
        if gitignore.exists():
            with gitignore.open("a") as f:
                if not existing.endswith("\n"):
                    f.write("\n")
                f.write(f"{BASELINE_GITIGNORE_RULE}\n")
        else:
            gitignore.write_text(f"{BASELINE_GITIGNORE_RULE}\n", encoding="utf-8")
        print(f"  Updated .gitignore ({BASELINE_GITIGNORE_RULE})")

    # Not every project is a git repo (e.g. init before `git init`); skip cleanup
    # there. `git rev-parse --git-dir` is the standard repo probe.
    probe = subprocess.run(
        ["git", "rev-parse", "--git-dir"],
        cwd=str(project_root), capture_output=True, text=True,
    )
    if probe.returncode != 0:
        return

    # List tracked files under any change's baseline/ dir, relative to repo root.
    # Pathspec globs are unreliable across git versions when invoked without a
    # shell (subprocess passes `*` literally and git's pathspec matching of the
    # `baseline/` segment is inconsistent), so list all tracked files under the
    # changes tree and filter in Python — paths are repo-root-relative already.
    ls = subprocess.run(
        ["git", "ls-files", "--", ".cairness/changes/"],
        cwd=str(project_root), capture_output=True, text=True,
    )
    if ls.returncode != 0:
        return
    tracked = [
        line.strip() for line in ls.stdout.splitlines()
        if line.strip() and f"/baseline/" in f"{line.strip()}/"
    ]
    if not tracked:
        return
    rm = subprocess.run(
        ["git", "rm", "--cached", "--quiet", "--", *tracked],
        cwd=str(project_root), capture_output=True, text=True,
    )
    if rm.returncode == 0:
        print(f"  Untracked {len(tracked)} committed baseline file(s) "
              f"(kept on disk; will be dropped on next commit):")
        for path in tracked:
            print(f"    {path}")
    else:
        # Don't fail the install/update over a git index issue; surface it.
        print(f"  warning: could not untrack committed baseline files: {rm.stderr.strip()}",
              file=sys.stderr)


def _install_git_hooks(
    project_root: Path, framework_root: Path | None = None
) -> None:
    """Install Cairness git hooks from .claude/hooks/ into .git/hooks/.

    Only the hooks listed in the hook_map are installed; framework hooks
    (like no-spec-no-code.py) that are Claude Code PreToolUse hooks, not
    git hooks, stay in .claude/hooks/ only.
    """
    hooks_src = framework_root or (project_root / ".claude")
    hooks_src = hooks_src / "hooks"
    git_hooks_dir = project_root / ".git" / "hooks"

    # Not a git repo — skip (same guard as _ensure_baseline_gitignored).
    probe = subprocess.run(
        ["git", "rev-parse", "--git-dir"],
        cwd=str(project_root), capture_output=True, text=True,
    )
    if probe.returncode != 0:
        return

    # Map: framework hook filename (under .claude/hooks/) → git hook name.
    hook_map = {"pre-commit": "pre-commit"}

    for fw_name, git_name in hook_map.items():
        src = hooks_src / fw_name
        if not src.is_file():
            continue
        dst = git_hooks_dir / git_name

        if dst.exists():
            try:
                content = dst.read_text(encoding="utf-8", errors="replace")
            except OSError:
                content = ""
            if "Cairness" in content:
                # Existing Cairness-managed hook — update in place.
                shutil.copy2(src, dst)
                dst.chmod(0o755)
            else:
                # Non-Cairness hook exists — back up, warn, install.
                backup = dst.with_suffix(".bak")
                shutil.move(str(dst), str(backup))
                shutil.copy2(src, dst)
                dst.chmod(0o755)
                print(f"  ⚠ Existing .git/hooks/{git_name} backed up to "
                      f".git/hooks/{git_name}.bak")
        else:
            shutil.copy2(src, dst)
            dst.chmod(0o755)


def sync_project(data_dir, project_root):
    """Update the metadata-selected project adapter from the system install."""
    project_root = Path(project_root).resolve()
    metadata = read_install_metadata(project_root, strict=True)
    legacy = not metadata and (project_root / ".claude" / "VERSION").is_file()
    adapter = metadata.get("adapter") or ("claude-code" if legacy else "")
    if not adapter:
        version = (data_dir / "VERSION").read_text().strip()
        print(f"System installation is v{version}.")
        print("Run 'cc-cairn init' in a project directory to install the framework.")
        return False

    plan = _adapter_installation_plan(data_dir, project_root, adapter)
    framework_prefix = metadata.get("framework_prefix") or plan.framework_prefix
    # Validate persisted layout metadata before using it as a filesystem path.
    framework_dir = _framework_root_from_prefix(project_root, framework_prefix)
    if not framework_dir.exists():
        version = (data_dir / "VERSION").read_text().strip()
        print(f"System installation is v{version}.")
        print(
            f"Configured framework layout {framework_prefix}/ is missing; "
            "run 'cc-cairn init' to install it."
        )
        return False
    _require_custom_layout_identity(
        framework_dir,
        adapter=adapter,
        contract_prefix=plan.framework_prefix,
        selected_prefix=framework_prefix,
    )

    new_commit = read_commit_hash(data_dir)
    old_commit = read_commit_hash(framework_dir)

    new_ver = (data_dir / "VERSION").read_text().strip()
    version_file = framework_dir / "VERSION"
    project_ver = (
        version_file.read_text(encoding="utf-8").strip()
        if version_file.is_file()
        else "unknown"
    )

    if new_commit and old_commit and new_commit == old_commit:
        print(f"Project already up to date (v{project_ver}, {old_commit[:7]}).")
        _publish_install_result(
            project_root,
            adapter=plan.adapter,
            framework_prefix=framework_prefix,
            report={
                "version": 1,
                "status": "passed",
                "adapter": plan.adapter,
                "source_layout": framework_prefix,
                "target_layout": framework_prefix,
                "from_version": project_ver,
                "to_version": new_ver,
                "backup": "",
                "legacy_migration": legacy,
                "operations": [],
                "overwritten_modified_files": [],
                "dropped_stale_files": [],
                "preserved_files": [],
            },
        )
        return False

    changes = _upgrade_file_changes(data_dir, framework_dir)
    print(f"Updating project {framework_prefix}/: v{project_ver} → v{new_ver}")
    metadata_path = project_root / ".cairness" / "install.yaml"
    report_path = project_root / UPGRADE_REPORT_RELATIVE
    metadata_snapshot = _file_snapshot(metadata_path)
    report_snapshot = _file_snapshot(report_path)
    hook_path = project_root / ".git" / "hooks" / "pre-commit"
    hook_backup_path = hook_path.with_suffix(".bak")
    hook_snapshot = _file_state_snapshot(hook_path)
    hook_backup_snapshot = _file_state_snapshot(hook_backup_path)
    backup = None
    swapped = False
    try:
        backup = _replace_framework_dir(
            data_dir,
            framework_dir,
            label=f"project {framework_prefix}/",
        )
        swapped = True
    except UpgradeSafetyError as exc:
        print(f"error: {exc}", file=sys.stderr)
        print("hint: if this is intentionally a non-Cairness directory, run "
              "'cc-cairn init' with overwrite, or remove it manually.", file=sys.stderr)
        sys.exit(1)
    try:
        operations = _execute_adapter_operations(plan, framework_dir)
        # Re-install / update git hooks.
        _install_git_hooks(project_root, framework_dir)
        _publish_install_result(
            project_root,
            adapter=plan.adapter,
            framework_prefix=framework_prefix,
            report={
                "version": 1,
                "status": "passed",
                "adapter": plan.adapter,
                "source_layout": framework_prefix,
                "target_layout": framework_prefix,
                "from_version": project_ver,
                "to_version": new_ver,
                "backup": str(backup) if backup else "",
                "legacy_migration": legacy,
                "operations": operations,
                **changes,
            },
        )
    except Exception:
        try:
            if swapped:
                _restore_failed_adapter_swap(framework_dir, backup)
        finally:
            _restore_file_snapshot(metadata_path, metadata_snapshot)
            _restore_file_snapshot(report_path, report_snapshot)
            _restore_file_state_snapshot(hook_path, hook_snapshot)
            _restore_file_state_snapshot(hook_backup_path, hook_backup_snapshot)
        raise
    # Backfill the transient-baseline ignore rule after the installation
    # transaction has committed; this cleanup is not part of update identity.
    _ensure_baseline_gitignored(project_root)
    print(f"Project updated to v{new_ver}. Local additions were preserved; "
          f"previous {framework_prefix}/ backed up to {framework_dir.name}.bak.")
    return True


def cmd_update():
    data_dir = get_data_dir()
    if not data_dir.exists():
        sys.exit(f"Framework not installed. Run 'cairn_install' from the Cairness repo first.")

    repo = ensure_repo()
    sync_system_install(data_dir, repo)
    sync_project(data_dir, Path.cwd())


def cmd_version():
    data_dir = get_data_dir()
    installed_ver = "not installed"
    installed_commit = ""
    if data_dir.exists():
        vf = data_dir / "VERSION"
        if vf.exists():
            try:
                installed_ver = read_version(vf)
            except VersionMetadataError:
                installed_ver = "invalid metadata"
        cf = data_dir / "COMMIT"
        if cf.exists():
            installed_commit = cf.read_text().strip()[:7]

    project_ver = "not initialized"
    project_commit = ""
    project_framework = resolve_framework_root(Path.cwd())
    if project_framework.exists():
        vf = project_framework / "VERSION"
        if vf.exists():
            try:
                project_ver = read_version(vf)
            except VersionMetadataError:
                project_ver = "invalid metadata"
        cf = project_framework / "COMMIT"
        if cf.exists():
            project_commit = cf.read_text().strip()[:7]

    sys_commit = f" ({installed_commit})" if installed_commit else ""
    proj_commit = f" ({project_commit})" if project_commit else ""
    system_display = f"v{installed_ver}{sys_commit}" if installed_ver not in {"not installed", "invalid metadata"} else installed_ver
    project_display = f"v{project_ver}{proj_commit}" if project_ver not in {"not initialized", "invalid metadata"} else project_ver
    print(f"cc-cairn (system): {system_display}")
    print(f"Project ({Path.cwd()}): {project_display}")

    repo = find_repo()
    if repo is None:
        print("Source: not found (update availability unknown)")
        return
    source_version_file = repo / "cairn-core" / "VERSION"
    try:
        source_version = read_version(source_version_file)
    except VersionMetadataError:
        source_version = "invalid metadata"
    source_display = f"v{source_version}" if source_version != "invalid metadata" else source_version
    print(f"Source ({repo}): {source_display}")
    if source_version != "invalid metadata" and installed_ver not in {"not installed", "invalid metadata", source_version}:
        print(f"Update available: system v{installed_ver} → v{source_version}")
    if source_version != "invalid metadata" and project_ver not in {"not initialized", "invalid metadata", source_version}:
        print(f"Update available: project v{project_ver} → v{source_version}")


def cmd_doctor(argv):
    parser = argparse.ArgumentParser(prog="cc-cairn doctor")
    parser.add_argument("--json", action="store_true", help="emit the complete structured readiness report")
    parser.add_argument("--fix", action="store_true", help="show a safe repair plan (dry-run by default)")
    parser.add_argument("--apply", action="store_true", help="apply the safe repair plan; requires --fix")
    args = parser.parse_args(argv)
    if args.apply and not args.fix:
        parser.error("--apply requires --fix")

    project_root = Path.cwd().resolve()
    project_framework = resolve_framework_root(project_root, strict_metadata=False)
    framework_root = project_framework if (project_framework / "VERSION").is_file() else Path(__file__).resolve().parent
    system_root = get_data_dir()
    report = build_doctor_report(project_root, framework_root, system_root)

    if args.fix:
        actions = fix_plan(report)
        if args.apply:
            try:
                apply_fix_plan(actions)
            except OSError as exc:
                print(f"E_DOCTOR_FIX {exc}", file=sys.stderr)
                raise SystemExit(1)
            report = build_doctor_report(project_root, framework_root, system_root)
            report["fix"] = {"mode": "applied", "actions": actions}
        else:
            report["fix"] = {"mode": "dry-run", "actions": actions}

    if args.json:
        print(json.dumps(report, ensure_ascii=False, indent=2))
    else:
        print(f"Cairness Doctor: {report['status']}")
        summary = report["summary"]
        print(f"  Version: project={summary['versions']['project']} system={summary['versions']['system']}")
        print(f"  Config: {summary['config']['status']}")
        print(f"  Adapter: {summary['adapter']['name']} ({summary['adapter']['status']})")
        print(f"  CI: {summary['ci']['status']}")
        language = summary["language_profile"]
        print(f"  Language: {language['name'] or language['status']} ({language['source']})")
        onboarding = summary.get("onboarding", {})
        if onboarding:
            print(f"  Onboarding: {onboarding.get('status', 'unknown')}")
        if report["fix"]["mode"] == "dry-run":
            print("Safe repair plan (dry-run):")
            for action in report["fix"]["actions"]:
                print(f"  {action['code']} {action['action']} {action['path']}")
            if report["fix"]["actions"]:
                print("Run cc-cairn doctor --fix --apply to apply this plan.")
        for issue in report["issues"]:
            print(f"{issue['code']} {issue['path']}: {issue['message']}", file=sys.stderr)
            print(f"  cause: {issue['cause']}", file=sys.stderr)
            print(f"  fix: {issue['fix_hint']}", file=sys.stderr)
            print(f"  docs: {issue['doc_ref']}", file=sys.stderr)
    raise SystemExit(1 if report["status"] == "failed" else 0)


def cmd_config(argv):
    parser = argparse.ArgumentParser(prog="cc-cairn config")
    parser.add_argument("action", choices=("validate", "explain", "migrate"))
    parser.add_argument("key", nargs="?")
    parser.add_argument("--json", action="store_true")
    parser.add_argument("--apply", action="store_true")
    args = parser.parse_args(argv)
    path = resolve_framework_root(Path.cwd()) / "harness.config.yaml"
    if args.action == "migrate":
        if not path.is_file():
            print(f"E_CONFIG001 {path}: missing harness config", file=sys.stderr)
            raise SystemExit(1)
        content = path.read_text(encoding="utf-8")
        if any(line.strip().startswith("schema_version:") for line in content.splitlines()):
            print("harness config: already at schema_version 1")
            return
        if not args.apply:
            print("[dry-run] add schema_version: 1 as the first config field")
            return
        path.write_text("schema_version: 1\n" + content, encoding="utf-8")
        print("harness config: migrated to schema_version 1")
        return
    try:
        config = load_harness_config(path)
    except HarnessConfigError as exc:
        print(f"E_CONFIG001 {exc}", file=sys.stderr)
        raise SystemExit(1)
    if args.action == "validate":
        payload = {"status": "passed", "path": str(path)}
        print(json.dumps(payload) if args.json else "harness config: valid")
        return
    value = config.values
    if args.key:
        for part in args.key.split("."):
            value = value.get(part) if isinstance(value, dict) else None
        payload = {"key": args.key, "value": value, "source": config.source(args.key)}
    else:
        payload = {"values": config.values, "sources": config.sources}
    print(json.dumps(payload, ensure_ascii=False, indent=2))


def cmd_profile(argv):
    """Inspect or apply a user-facing product profile."""
    parser = argparse.ArgumentParser(prog="cc-cairn profile")
    parser.add_argument("action", choices=("show", "set"))
    parser.add_argument("profile", nargs="?", choices=("starter", "team", "regulated", "autonomous"))
    parser.add_argument("--apply", action="store_true", help="apply a set operation after showing its diff")
    parser.add_argument("--json", action="store_true")
    args = parser.parse_args(argv)
    if args.action == "show":
        if args.profile:
            parser.error("show does not accept a profile argument")
        payload = {"profiles": list_product_profiles()}
        print(json.dumps(payload, ensure_ascii=False, indent=2) if args.json else "\n".join(
            f"{item['id']}: {item['description']} ({item['runtime_profile']})"
            for item in payload["profiles"]
        ))
        return
    if not args.profile:
        parser.error("set requires a profile")
    config = resolve_framework_root(Path.cwd()) / "harness.config.yaml"
    try:
        plan = build_profile_plan(config, args.profile)
    except ValueError as exc:
        print(f"E_PROFILE001 {exc}", file=sys.stderr)
        raise SystemExit(1)
    if args.json and args.apply and plan["status"] == "changed":
        try:
            applied = apply_product_profile(config, args.profile)
        except ValueError as exc:
            print(f"E_PROFILE001 {exc}", file=sys.stderr)
            raise SystemExit(1)
        print(json.dumps({"status": "applied", "profile": applied}, ensure_ascii=False, indent=2))
        return
    if args.json:
        print(json.dumps(plan, ensure_ascii=False, indent=2))
    else:
        print(f"Product profile: {args.profile} -> {plan['target']['runtime_profile']}")
        print(f"Config: {plan['config']}")
        print(plan["diff"] or "No changes required.")
    if plan["status"] == "unchanged":
        return
    if not args.apply and args.json:
        return
    if not args.apply:
        raise SystemExit("Profile change is a preview. Re-run with --apply to write it.")
    try:
        applied = apply_product_profile(config, args.profile)
    except ValueError as exc:
        print(f"E_PROFILE001 {exc}", file=sys.stderr)
        raise SystemExit(1)
    if args.json:
        print(json.dumps({"status": "applied", "profile": applied}, ensure_ascii=False, indent=2))
    else:
        print(f"Applied product profile: {args.profile}")


def cmd_explain(argv):
    parser = argparse.ArgumentParser(prog="cc-cairn explain")
    parser.add_argument("command", help="registered runtime command, for example cc-apply")
    parser.add_argument("--change", help="change ID used to resolve change-scoped readiness")
    parser.add_argument("--root", help="explicit Cairness project root")
    parser.add_argument("--json", action="store_true", help="emit the structured effective contract")
    args = parser.parse_args(argv)
    try:
        context = load_harness_context(
            explicit_root=Path(args.root) if args.root else None,
            start=None if args.root else Path.cwd(),
        )
    except HarnessContextError as exc:
        print(f"E_CONTEXT001 {exc}", file=sys.stderr)
        raise SystemExit(2)

    report = build_effective_contract(context, args.command, change_id=args.change)
    if args.json:
        print(json.dumps(report, ensure_ascii=False, indent=2))
    elif report["status"] == "failed":
        for issue in report["issues"]:
            print(f"{issue['code']} {issue['path']}: {issue['message']}", file=sys.stderr)
    else:
        print(f"Effective contract: {report['command']}")
        print(f"  Profile: {report['profile']['id']} ({report['profile']['source']})")
        language = report["language_profile"]
        print(f"  Language: {language['id'] or language['status']} ({language['source']})")
        workspace = report["workspace_profile"]
        print(f"  Workspace: {workspace['id'] or workspace['status']}")
        print(f"  Adapter: {report['adapter']['name']} ({report['adapter']['root']})")
        print(f"  Readiness: {report['readiness']['status']}")
        print(f"  Reads: {len(report['reads']['always'])} always, {len(report['reads']['conditional'])} conditional groups")
        print(f"  Writes: {len(report['writes'])}")
        print(f"  Gates: {', '.join(report['gates']) or 'none'}")
        topics = report["topic_rules"]
        print(f"  Topic Rules: {len(topics['always'])} always, {len(topics['triggered'])} triggered")
        budget = report["context_budget"]
        print(f"  Context budget: {budget['token_limit'] or 'unconfigured'} tokens")
        for item in report["readiness"]["unmet"]:
            print(f"  {item['code']}: {item['message']}")
    raise SystemExit(1 if report["status"] == "failed" else 0)


KNOWLEDGE_INDEX_CATEGORIES_FALLBACK = [
    ("domain-rules", "业务规则"),
    ("technical-conventions", "技术约定"),
    ("pitfalls", "踩坑记录"),
    ("module-guides", "模块指南"),
    ("decision-records", "历史方案"),
    ("data-assets", "数据资产"),
    ("non-functional", "非功能性约束"),
    ("external-references", "外部依赖引用"),
]
KNOWLEDGE_INDEX_FORBIDDEN_SUBDIRS_FALLBACK = {"refinement-candidates"}
KNOWLEDGE_INIT_SUBDIRS_FALLBACK = [s for s, _ in KNOWLEDGE_INDEX_CATEGORIES_FALLBACK] + ["refinement-candidates"]


def _resolve_catalog_path(project_root):
    """Locate knowledge-categories.yaml. Prefer project, fall back to system."""
    candidates = [
        resolve_framework_root(project_root) / KNOWLEDGE_CATALOG_REL,
        get_data_dir() / KNOWLEDGE_CATALOG_REL,
    ]
    for c in candidates:
        if c.is_file():
            return c
    return None


def _load_knowledge_catalog(project_root):
    """Return list of category dicts; fall back to hardcoded defaults on any error.

    Each entry has: subdir, display_name, description, indexed, created_by_init.
    """
    catalog_path = _resolve_catalog_path(project_root)
    if catalog_path is None:
        return None
    try:
        import yaml  # type: ignore
    except ImportError:
        return None
    try:
        data = yaml.safe_load(catalog_path.read_text(encoding="utf-8"))
    except Exception:
        return None
    if not isinstance(data, dict):
        return None
    cats = data.get("categories")
    if not isinstance(cats, list) or not cats:
        return None
    out = []
    for c in cats:
        if not isinstance(c, dict):
            return None
        if not all(k in c for k in ("subdir", "display_name", "indexed", "created_by_init")):
            return None
        out.append(c)
    return out


def _knowledge_init_subdirs(project_root):
    cats = _load_knowledge_catalog(project_root)
    if cats is None:
        return list(KNOWLEDGE_INIT_SUBDIRS_FALLBACK)
    return [c["subdir"] for c in cats if c.get("created_by_init")]


def _knowledge_indexed_categories(project_root):
    """Return [(subdir, display_name), ...] for categories that participate in index.md."""
    cats = _load_knowledge_catalog(project_root)
    if cats is None:
        return list(KNOWLEDGE_INDEX_CATEGORIES_FALLBACK)
    return [(c["subdir"], c["display_name"]) for c in cats if c.get("indexed")]


def _knowledge_forbidden_subdirs(project_root):
    cats = _load_knowledge_catalog(project_root)
    if cats is None:
        return set(KNOWLEDGE_INDEX_FORBIDDEN_SUBDIRS_FALLBACK)
    return {c["subdir"] for c in cats if not c.get("indexed")}


def _knowledge_root(project_root):
    return project_root / ".cairness" / "knowledge"


def _resolve_knowledge_path(project_root, raw_path):
    """Return (subdir, rel_path_posix) or raise ValueError."""
    p = Path(raw_path).expanduser()
    if not p.is_absolute():
        p = (project_root / p).resolve()
    else:
        p = p.resolve()

    knowledge_root = _knowledge_root(project_root).resolve()
    try:
        rel = p.relative_to(knowledge_root)
    except ValueError:
        raise ValueError(
            f"path is not under .cairness/knowledge/: {raw_path}"
        )

    parts = rel.parts
    if len(parts) < 2:
        raise ValueError(
            f"path must be inside a category subdir (e.g. domain-rules/foo.md): {raw_path}"
        )
    subdir = parts[0]
    if subdir in _knowledge_forbidden_subdirs(project_root):
        raise ValueError(
            f"refinement-candidates/ is not registered in index.md: {raw_path}"
        )
    valid_subdirs = {s for s, _ in _knowledge_indexed_categories(project_root)}
    if subdir not in valid_subdirs:
        raise ValueError(
            f"unknown category subdir '{subdir}'. Valid: {sorted(valid_subdirs)}"
        )
    if p.suffix.lower() != ".md":
        raise ValueError(f"only .md files can be registered: {raw_path}")
    if not p.is_file():
        raise ValueError(f"file not found: {raw_path}")

    return subdir, rel.as_posix()


def _extract_keyword_draft(content, fallback_stem):
    for line in content.splitlines():
        s = line.strip()
        if not s:
            continue
        m = re.match(r"^#{1,6}\s+(.+?)\s*$", s)
        if m:
            return m.group(1).strip()
        return s[:30].strip()
    return fallback_stem.replace("-", " ").replace("_", " ").strip() or fallback_stem


def _extract_desc_draft(content):
    lines = content.splitlines()
    skipped_h1 = False
    for line in lines:
        s = line.strip()
        if not s:
            continue
        if not skipped_h1 and re.match(r"^#{1,6}\s+", s):
            skipped_h1 = True
            continue
        clean = re.sub(r"\*\*", "", s)
        clean = re.sub(r"^\s*[>#]+\s*", "", clean).strip()
        if clean:
            return clean[:60]
    return "TODO: 补充一句话说明"


_HTML_COMMENT_RE = re.compile(r"<!--.*?-->", re.DOTALL)


def _strip_html_comments(text):
    return _HTML_COMMENT_RE.sub("", text)


def _parse_existing_entries(index_text):
    """Return set of registered relative paths and dict keyword -> path.

    Skips content inside HTML comments so example entries in templates
    don't trigger false-positive conflicts.
    """
    paths = set()
    keywords = {}
    entry_re = re.compile(r"\*\*(.+?)\*\*\s*:\s*(.+)\s*→\s*(\S+)\s*$")
    cleaned = _strip_html_comments(index_text)
    for line in cleaned.splitlines():
        m = entry_re.search(line)
        if m:
            kw, _, path = m.group(1).strip(), m.group(2), m.group(3).strip()
            paths.add(path)
            keywords[kw] = path
    return paths, keywords


def _find_entry_lines(index_text, target_path):
    """Return list of (line_index_in_raw, keyword, desc) for entries matching path.

    Walks raw lines so the returned line indices are valid for line-based edits.
    Tracks multi-line HTML comments so example triples inside `<!-- … -->`
    don't get matched (template example uses `文件路径` placeholder, but be safe).
    """
    entry_re = re.compile(r"\*\*(.+?)\*\*\s*:\s*(.+)\s*→\s*(\S+)\s*$")
    in_comment = False
    out = []
    for idx, line in enumerate(index_text.splitlines()):
        scan = line
        if in_comment:
            close = scan.find("-->")
            if close == -1:
                continue
            scan = scan[close + 3:]
            in_comment = False
        # strip same-line comments and detect open comment
        while True:
            opn = scan.find("<!--")
            if opn == -1:
                break
            cls = scan.find("-->", opn + 4)
            if cls == -1:
                scan = scan[:opn]
                in_comment = True
                break
            scan = scan[:opn] + scan[cls + 3:]
        m = entry_re.search(scan)
        if not m:
            continue
        kw = m.group(1).strip()
        desc = m.group(2).strip()
        path = m.group(3).strip()
        if path == target_path:
            out.append((idx, kw, desc))
    return out


def _find_section_insert_point(index_text, subdir):
    """Locate where to insert a new entry for subdir.

    Strategy: find a heading line whose text contains '({subdir}/)' marker.
    Return (line_index_after_section_end, heading_level) or (None, None) if not found.
    """
    lines = index_text.splitlines()
    marker = f"({subdir}/)"
    section_start = None
    section_level = None
    for i, line in enumerate(lines):
        m = re.match(r"^(#{1,6})\s+(.+)$", line)
        if m and marker in m.group(2):
            section_start = i
            section_level = len(m.group(1))
            break
    if section_start is None or section_level is None:
        return None, None

    end = len(lines)
    for j in range(section_start + 1, len(lines)):
        line = lines[j]
        m = re.match(r"^(#{1,6})\s+", line)
        if m and len(m.group(1)) <= section_level:
            end = j
            break
        if re.match(r"^-{3,}\s*$", line.strip()):
            end = j
            break
    while end > section_start + 1 and lines[end - 1].strip() == "":
        end -= 1
    return end, section_level


def _insert_entry(lines, insert_at, entry_line):
    """Insert entry_line at insert_at, padding with blank lines as needed.

    Returns (new_lines, shift) where shift is the number of lines added.
    """
    out = list(lines)
    inserted = []
    need_blank_before = insert_at > 0 and out[insert_at - 1].strip() != ""
    if need_blank_before:
        inserted.append("")
    inserted.append(entry_line)
    next_line = out[insert_at] if insert_at < len(out) else ""
    if next_line.strip() != "":
        inserted.append("")
    out[insert_at:insert_at] = inserted
    return out, len(inserted)


def _append_new_section(lines, subdir, display_name, entry_line):
    out = list(lines)
    while out and out[-1].strip() == "":
        out.pop()
    out.append("")
    out.append("---")
    out.append("")
    out.append(f"## {display_name} ({subdir}/)")
    out.append("")
    out.append(entry_line)
    out.append("")
    return out


def _commit_index_text(project_root, index_path, original_text, new_text):
    """Write new_text atomically; if cc-index-check reports new errors, rollback.

    Returns (ok, message). On success ok=True. On rollback ok=False with a
    user-facing message describing the new error count.
    """
    pre_error_count = _count_index_errors(project_root, original_text)
    tmp = index_path.with_suffix(index_path.suffix + ".tmp")
    tmp.write_text(new_text, encoding="utf-8")
    os.replace(tmp, index_path)
    post_error_count = _count_index_errors(project_root, new_text)
    if post_error_count is not None and pre_error_count is not None \
            and post_error_count > pre_error_count:
        index_path.write_text(original_text, encoding="utf-8")
        checker = _index_checker_path(project_root)
        checker_display = checker.relative_to(Path(project_root).resolve()).as_posix()
        return False, (
            f"cc-index-check reported {post_error_count - pre_error_count} new "
            f"error(s) after write; rolled back. Run "
            f"{checker_display} to inspect."
        )
    return True, ""


def _strip_blank_pad(lines, idx):
    """Remove a blank line immediately after `idx` if both before and after are blank.

    Used after deleting an entry so we don't accumulate consecutive blanks.
    """
    if 0 <= idx - 1 < len(lines) and idx < len(lines):
        if lines[idx - 1].strip() == "" and lines[idx].strip() == "":
            del lines[idx]


def _handle_remove(project_root, index_path, paths, apply):
    """Remove entries matching the given paths from index.md.

    paths are accepted in the same form `add-knowledge` accepts (absolute, relative,
    or category/file.md), but we don't require the file to still exist on disk —
    the whole point of `--remove` is cleaning up stale entries.
    """
    knowledge_root = (project_root / ".cairness" / "knowledge").resolve()
    targets = []
    errors = []
    for raw in paths:
        p = Path(raw).expanduser()
        if not p.is_absolute():
            p = (project_root / p)
        try:
            rel = Path(p).resolve().relative_to(knowledge_root).as_posix()
        except ValueError:
            try:
                rel = Path(raw).as_posix()
                # accept bare category/file.md if it round-trips
                if not rel or rel.startswith("/") or ".." in rel.split("/"):
                    raise ValueError
            except Exception:
                errors.append(f"path is not under .cairness/knowledge/: {raw}")
                continue
        targets.append(rel)

    if errors:
        for e in errors:
            print(f"error: {e}", file=sys.stderr)
        sys.exit(1)

    original_text = index_path.read_text(encoding="utf-8")
    lines = original_text.splitlines()

    removals = []  # (rel, line_index, kw)
    not_found = []
    for rel in targets:
        hits = _find_entry_lines(original_text, rel)
        if not hits:
            not_found.append(rel)
            continue
        for line_idx, kw, _ in hits:
            removals.append((rel, line_idx, kw))

    if not removals:
        for rel in not_found:
            print(f"not registered: {rel}")
        return

    # Sort descending so deletion doesn't shift earlier indices
    removals.sort(key=lambda r: r[1], reverse=True)

    if not apply:
        print(f"[dry-run] {len(removals)} entries to remove:")
        for rel, line_idx, kw in sorted(removals, key=lambda r: r[1]):
            print(f"  - L{line_idx + 1}: **{kw}** → {rel}")
        for rel in not_found:
            print(f"  (not registered) {rel}")
        print()
        print("Run with --apply to write changes.")
        return

    for _, line_idx, _ in removals:
        if 0 <= line_idx < len(lines):
            del lines[line_idx]
            _strip_blank_pad(lines, line_idx)

    new_text = "\n".join(lines)
    if not new_text.endswith("\n"):
        new_text += "\n"

    ok, msg = _commit_index_text(project_root, index_path, original_text, new_text)
    if not ok:
        print(f"error: {msg}", file=sys.stderr)
        sys.exit(1)
    for rel in not_found:
        print(f"not registered: {rel}")
    print(f"removed {len(removals)} entries from {index_path.relative_to(project_root)}")


def _handle_rename(project_root, index_path, old_raw, new_raw, apply):
    """Rename a single entry's path from old → new (keyword/description preserved).

    `new` must resolve to a valid registered category and the file must exist.
    `old` does not need to exist on disk.
    """
    knowledge_root = (project_root / ".cairness" / "knowledge").resolve()

    old_p = Path(old_raw).expanduser()
    if not old_p.is_absolute():
        old_p = project_root / old_p
    try:
        old_rel = Path(old_p).resolve().relative_to(knowledge_root).as_posix()
    except ValueError:
        sys.exit(f"old path is not under .cairness/knowledge/: {old_raw}")

    try:
        _, new_rel = _resolve_knowledge_path(project_root, new_raw)
    except ValueError as e:
        sys.exit(str(e))

    original_text = index_path.read_text(encoding="utf-8")
    hits = _find_entry_lines(original_text, old_rel)
    if not hits:
        sys.exit(f"not registered: {old_rel}")
    if len(hits) > 1:
        sys.exit(
            f"old path has {len(hits)} entries; resolve duplicates first via "
            f"--remove and then re-register"
        )
    line_idx, kw, desc = hits[0]

    existing_paths, _ = _parse_existing_entries(original_text)
    if new_rel != old_rel and new_rel in existing_paths:
        sys.exit(f"new path already registered: {new_rel}")

    lines = original_text.splitlines()
    raw_line = lines[line_idx]
    # Replace the path token at end of triple. Anchor on '→' to avoid touching
    # similar text earlier on the line.
    arrow = raw_line.rfind("→")
    if arrow == -1:
        sys.exit("internal: failed to locate arrow on entry line")
    new_line = raw_line[:arrow + 1] + " " + new_rel
    # Preserve trailing whitespace if any
    lines[line_idx] = new_line

    if not apply:
        print("[dry-run] rename:")
        print(f"  - {old_rel}")
        print(f"  + {new_rel}    (kw='{kw}', desc='{desc}')")
        print()
        print("Run with --apply to write changes.")
        return

    new_text = "\n".join(lines)
    if not new_text.endswith("\n"):
        new_text += "\n"

    ok, msg = _commit_index_text(project_root, index_path, original_text, new_text)
    if not ok:
        print(f"error: {msg}", file=sys.stderr)
        sys.exit(1)
    print(f"renamed {old_rel} → {new_rel} in {index_path.relative_to(project_root)}")


def cmd_add_knowledge(argv):
    parser = argparse.ArgumentParser(
        prog="cc-cairn add-knowledge",
        description="Register knowledge files into .cairness/knowledge/index.md",
    )
    parser.add_argument("paths", nargs="+", help="knowledge file path(s) under .cairness/knowledge/<category>/")
    parser.add_argument("--apply", action="store_true", help="actually write to index.md (default: dry-run)")
    parser.add_argument("--keyword", help="override keyword (only valid with a single path)")
    parser.add_argument("--desc", help="override description (only valid with a single path)")
    parser.add_argument("--remove", action="store_true", help="remove the given path(s) from index.md instead of registering")
    parser.add_argument("--rename", action="store_true", help="rename a single entry: pass <old-path> <new-path>")
    args = parser.parse_args(argv)

    if args.remove and args.rename:
        sys.exit("--remove and --rename are mutually exclusive")
    if (args.keyword or args.desc) and (args.remove or args.rename):
        sys.exit("--keyword/--desc are not valid with --remove/--rename")
    if (args.keyword or args.desc) and len(args.paths) != 1:
        sys.exit("--keyword/--desc only valid when registering a single path")

    project_root = Path.cwd()
    index_path = project_root / ".cairness" / "knowledge" / "index.md"
    if not index_path.is_file():
        sys.exit(
            "index.md not found. Run 'cc-cairn init' first or create "
            ".cairness/knowledge/index.md."
        )

    if args.remove:
        _handle_remove(project_root, index_path, args.paths, args.apply)
        return
    if args.rename:
        if len(args.paths) != 2:
            sys.exit("--rename requires exactly two paths: <old> <new>")
        _handle_rename(project_root, index_path, args.paths[0], args.paths[1], args.apply)
        return

    resolved = []
    errors = []
    for raw in args.paths:
        try:
            subdir, rel = _resolve_knowledge_path(project_root, raw)
        except ValueError as e:
            errors.append(str(e))
            continue
        resolved.append((subdir, rel, raw))

    if errors:
        for e in errors:
            print(f"error: {e}", file=sys.stderr)
        sys.exit(1)

    index_text = index_path.read_text(encoding="utf-8")
    existing_paths, existing_keywords = _parse_existing_entries(index_text)

    drafts = []
    skip_already = []
    for subdir, rel, raw in resolved:
        if rel in existing_paths:
            skip_already.append(rel)
            continue
        file_path = project_root / ".cairness" / "knowledge" / rel
        content = file_path.read_text(encoding="utf-8")
        if args.keyword:
            kw = args.keyword.strip()
        else:
            kw = _extract_keyword_draft(content, file_path.stem)
        if args.desc:
            desc = args.desc.strip()
        else:
            desc = _extract_desc_draft(content)
        drafts.append((subdir, rel, kw, desc))

    seen_kw_in_batch = {}
    kw_conflicts = []
    for subdir, rel, kw, desc in drafts:
        if kw in existing_keywords and existing_keywords[kw] != rel:
            kw_conflicts.append((kw, rel, existing_keywords[kw]))
        if kw in seen_kw_in_batch and seen_kw_in_batch[kw] != rel:
            kw_conflicts.append((kw, rel, seen_kw_in_batch[kw]))
        seen_kw_in_batch[kw] = rel

    if kw_conflicts:
        for kw, new_path, existing in kw_conflicts:
            print(
                f"error: keyword conflict: '{kw}' already used by {existing} (new: {new_path})",
                file=sys.stderr,
            )
        print("hint: pass --keyword to override (single-path mode only)", file=sys.stderr)
        sys.exit(1)

    if not drafts and not skip_already:
        print("nothing to do.")
        return
    if not drafts:
        for p in skip_already:
            print(f"already registered: {p}")
        return

    by_subdir = {}
    for subdir, rel, kw, desc in drafts:
        by_subdir.setdefault(subdir, []).append((rel, kw, desc))

    if not args.apply:
        print(f"[dry-run] {len(drafts)} entries to register:")
        for p in skip_already:
            print(f"  (skip, already registered) {p}")
        category_map = dict(_knowledge_indexed_categories(project_root))
        for subdir, items in by_subdir.items():
            display = category_map[subdir]
            print()
            print(f"  ## {display} ({subdir}/)")
            for rel, kw, desc in items:
                print(f"    + **{kw}** : {desc} → {rel}")
        print()
        print("Run with --apply to write changes.")
        return

    lines = index_text.splitlines()
    category_map = dict(_knowledge_indexed_categories(project_root))
    inserted_count = 0
    for subdir, items in by_subdir.items():
        for rel, kw, desc in items:
            entry_line = f"- **{kw}** : {desc} → {rel}"
            insert_at, _ = _find_section_insert_point("\n".join(lines), subdir)
            if insert_at is None:
                lines = _append_new_section(lines, subdir, category_map[subdir], entry_line)
            else:
                lines, _ = _insert_entry(lines, insert_at, entry_line)
            inserted_count += 1

    new_text = "\n".join(lines)
    if not new_text.endswith("\n"):
        new_text += "\n"

    ok, msg = _commit_index_text(project_root, index_path, index_text, new_text)
    if not ok:
        print(f"error: {msg}", file=sys.stderr)
        sys.exit(1)

    for p in skip_already:
        print(f"already registered: {p}")
    print(f"wrote {inserted_count} entries to {index_path.relative_to(project_root)}")


def _index_checker_path(project_root):
    return resolve_framework_root(project_root) / "scripts" / "cc-index-check"


def _count_index_errors(project_root, index_text):
    """Run cc-index-check against given index content (via temp file).

    Returns error count, or None if the lint script is unavailable / errored.
    """
    lint_script = _index_checker_path(project_root)
    if not lint_script.is_file():
        return None
    with tempfile.TemporaryDirectory() as td:
        td_path = Path(td)
        knowledge_src = project_root / ".cairness" / "knowledge"
        knowledge_dst = td_path / ".cairness" / "knowledge"
        # Copy the knowledge tree so path-existence checks resolve, but write
        # our candidate index.md instead of the on-disk one.
        shutil.copytree(knowledge_src, knowledge_dst, symlinks=True)
        (knowledge_dst / "index.md").write_text(index_text, encoding="utf-8")
        try:
            res = subprocess.run(
                [sys.executable, str(lint_script), "--json", "--root", str(td_path)],
                capture_output=True, text=True, timeout=15,
            )
        except (subprocess.TimeoutExpired, OSError):
            return None
        if res.returncode == 2:
            return None
        try:
            data = json.loads(res.stdout)
        except (ValueError, json.JSONDecodeError):
            return None
        return data.get("summary", {}).get("error", 0)


# ---------------------------------------------------------------------------
# Loop Engineering helpers
# ---------------------------------------------------------------------------

HARNESS_CONFIG_REL = "harness.config.yaml"
LOOP_CONFIG_REL = ".cairness/loop-config.yaml"
LOOP_CONFIG_TEMPLATE_REL = "templates/loop-config.yaml"

VALID_PROFILES = ("minimal", "standard", "strict", "loop")
DEFAULT_PROFILE = "standard"  # profile restored by 'cc-cairn loop disable'
LOOP_PROFILE = "loop"


def _read_current_profile(harness_cfg: Path) -> str:
    """Return the active profile value from harness.config.yaml, or 'unknown'."""
    try:
        return str(load_harness_config(harness_cfg).values["profile"])
    except (HarnessConfigError, KeyError):
        return "unknown"


def _set_profile(harness_cfg: Path, new_profile: str) -> None:
    """Replace the active 'profile:' line in harness.config.yaml."""
    if new_profile not in VALID_PROFILES:
        raise ValueError(
            f"Unknown profile '{new_profile}'. "
            f"Valid profiles: {', '.join(VALID_PROFILES)}"
        )
    text = harness_cfg.read_text(encoding="utf-8")
    lines = text.splitlines(keepends=True)
    replaced = False
    for i, line in enumerate(lines):
        stripped = line.strip()
        if stripped.startswith("#"):
            continue
        if stripped.startswith("profile:"):
            # Preserve leading whitespace (there is none for this top-level key)
            indent = line[: len(line) - len(line.lstrip())]
            lines[i] = f"{indent}profile: {new_profile}\n"
            replaced = True
            break
    if not replaced:
        raise ValueError(
            f"No 'profile:' key found in {harness_cfg}. "
            "The file may be corrupted — re-run 'cc-cairn init' to restore it."
        )
    harness_cfg.write_text("".join(lines), encoding="utf-8")


def _loop_config_summary(loop_cfg: Path) -> list[str]:
    """Return a short human-readable summary of the trust envelope."""
    lines_out = []
    if not loop_cfg.is_file():
        return lines_out
    for line in loop_cfg.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if stripped.startswith("#") or not stripped:
            continue
        for key in ("max_scope:", "max_residual_risk:"):
            if stripped.startswith(key):
                lines_out.append(f"  {stripped}")
    return lines_out


def cmd_loop(argv: list[str]) -> None:
    parser = argparse.ArgumentParser(
        prog="cc-cairn loop",
        description="Enable, disable, or inspect Loop Engineering mode.",
    )
    parser.add_argument(
        "action",
        choices=["enable", "disable", "status"],
        help=(
            "enable  — switch to loop profile and create loop-config.yaml if absent; "
            "disable — revert to standard profile; "
            "status  — show current loop mode state"
        ),
    )
    args = parser.parse_args(argv)

    project_root = Path.cwd()
    framework_root = resolve_framework_root(project_root)
    harness_cfg = framework_root / HARNESS_CONFIG_REL
    loop_cfg = project_root / LOOP_CONFIG_REL
    harness_cfg_display = harness_cfg.relative_to(project_root).as_posix()

    if not harness_cfg.is_file():
        sys.exit(
            f"{harness_cfg_display} not found. "
            "Run 'cc-cairn init' first to initialize the framework."
        )

    current_profile = _read_current_profile(harness_cfg)

    if args.action == "status":
        print(f"profile      : {current_profile}")
        loop_cfg_exists = loop_cfg.is_file()
        print(f"loop-config  : {'found' if loop_cfg_exists else 'not found'} ({LOOP_CONFIG_REL})")
        if current_profile == "loop":
            print("loop mode    : ENABLED ✓")
            summary = _loop_config_summary(loop_cfg)
            if summary:
                print("trust envelope:")
                for s in summary:
                    print(s)
            elif not loop_cfg_exists:
                print(
                    "warning: loop profile active but loop-config.yaml is missing.\n"
                    f"  Run 'cc-cairn loop enable' to create it from the template."
                )
        else:
            print(f"loop mode    : disabled (profile={current_profile})")

    elif args.action == "enable":
        # Step 1: ensure loop-config.yaml exists
        if loop_cfg.is_file():
            print(f"  {LOOP_CONFIG_REL} already exists — keeping as-is.")
        else:
            template = framework_root / LOOP_CONFIG_TEMPLATE_REL
            template_display = template.relative_to(project_root).as_posix()
            if not template.is_file():
                sys.exit(
                    f"Template not found: {template_display}\n"
                    f"Your {framework_root.name}/ may be outdated — run "
                    "'cc-cairn update' to refresh."
                )
            loop_cfg.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(template, loop_cfg)
            print(f"  Created {LOOP_CONFIG_REL} from template.")
            print(
                f"  → Edit {LOOP_CONFIG_REL} to set your trust envelope before running loop."
            )

        # Step 2: switch profile
        if current_profile == LOOP_PROFILE:
            print(f"  Profile is already '{LOOP_PROFILE}' — nothing changed.")
        else:
            _set_profile(harness_cfg, LOOP_PROFILE)
            print(f"  {harness_cfg_display}: profile set to '{LOOP_PROFILE}'.")

        print("\nLoop Engineering enabled.")
        print("Next: review .cairness/loop-config.yaml, then start Claude Code.")

    elif args.action == "disable":
        if current_profile == DEFAULT_PROFILE:
            print(f"  Profile is already '{DEFAULT_PROFILE}' — nothing changed.")
        else:
            _set_profile(harness_cfg, DEFAULT_PROFILE)
            print(f"  {harness_cfg_display}: profile set to '{DEFAULT_PROFILE}'.")

        print("\nLoop Engineering disabled (standard mode restored).")
        print(f"  {LOOP_CONFIG_REL} is preserved — re-enable with 'cc-cairn loop enable'.")


def main():
    if sys.version_info < MIN_PYTHON:
        v = ".".join(map(str, MIN_PYTHON))
        sys.exit(f"Cairness requires Python {v}+")

    if len(sys.argv) < 2:
        print("Usage: cc-cairn <init|onboard|profile|update|version|doctor|explain|config|loop|add-knowledge>")
        sys.exit(1)

    cmd = sys.argv[1]
    if cmd == "init":
        cmd_init()
    elif cmd == "onboard":
        cmd_onboard(sys.argv[2:])
    elif cmd == "profile":
        cmd_profile(sys.argv[2:])
    elif cmd == "update":
        cmd_update()
    elif cmd == "version":
        cmd_version()
    elif cmd == "doctor":
        cmd_doctor(sys.argv[2:])
    elif cmd == "explain":
        cmd_explain(sys.argv[2:])
    elif cmd == "config":
        cmd_config(sys.argv[2:])
    elif cmd == "loop":
        cmd_loop(sys.argv[2:])
    elif cmd == "add-knowledge":
        cmd_add_knowledge(sys.argv[2:])
    else:
        print(f"Unknown command: {cmd}")
        print("Usage: cc-cairn <init|onboard|profile|update|version|doctor|explain|config|loop|add-knowledge>")
        sys.exit(1)


if __name__ == "__main__":
    main()
